name: URI-ToDisk
version: 1.08
abstract: Create and manipulate URI to filesystem path mappings
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  Clone: 0.13
  List::Util: 1.11
  URI: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
